/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdbc9",
        "tertiary": "#6f2d0a",
        "primary-fixed-dim": "#ffb68c",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "primary-container": "#8b4513",
        "inverse-primary": "#ffb68c",
        "surface-container-low": "#f6f3f2",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#e1e1c9",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "background": "#fcf9f8",
        "on-tertiary-container": "#ffc1a7",
        "primary": "#6c2f00",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#54433a",
        "on-tertiary-fixed-variant": "#76320f",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e4e4cc",
        "surface-dim": "#dcd9d9",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1b1d0e",
        "on-error-container": "#93000a",
        "on-secondary-container": "#636451",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed": "#ffdbcd",
        "on-surface": "#1c1b1b",
        "on-primary-container": "#ffc29f",
        "surface-tint": "#934b19",
        "surface": "#fcf9f8",
        "secondary": "#5e604d",
        "tertiary-container": "#8d431f",
        "outline-variant": "#dac2b6",
        "on-primary-fixed-variant": "#753401",
        "outline": "#877369",
        "error": "#ba1a1a",
        "on-primary-fixed": "#321200",
        "secondary-fixed-dim": "#c8c8b0",
        "on-background": "#1c1b1b",
        "on-secondary-fixed-variant": "#474836",
        "tertiary-fixed-dim": "#ffb596",
        "inverse-surface": "#313030"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "section-gap": "80px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "button": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "button": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
